#!/bin/bash
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

pushd ..
bin/console doc:mig:mig -n
bin/console cache:clear

if which mdbook &> /dev/null; then
    pushd docs/
    mdbook build
fi
